# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: continuelogin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='continuelogin.proto',
  package='',
  serialized_pb=_b('\n\x13\x63ontinuelogin.proto\"}\n\x18SCDT_CONTINUE_LOGIN_INFO\x12\x15\n\rcontinue_days\x18\x01 \x01(\r\x12\x18\n\x10last_record_time\x18\x02 \x01(\r\x12\x18\n\x10re_signable_days\x18\x03 \x01(\r\x12\x16\n\x0eget_reward_bit\x18\x04 \x01(\r\"K\n\x19\x43SPKG_GET_CONLOGIN_REWARD\x12\x16\n\x0e\x63on_login_type\x18\x01 \x01(\r\x12\x16\n\x0e\x64\x61y_num_reward\x18\x02 \x01(\r\"v\n\x19SCPKG_NTF_CONLOGIN_REWARD\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x16\n\x0e\x63on_login_type\x18\x02 \x01(\r\x12\x31\n\x0e\x63on_login_info\x18\x03 \x01(\x0b\x32\x19.SCDT_CONTINUE_LOGIN_INFO\"v\n\x19SCPKG_GET_CONLOGIN_REWARD\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x16\n\x0e\x63on_login_type\x18\x02 \x01(\r\x12\x31\n\x0e\x63on_login_info\x18\x03 \x01(\x0b\x32\x19.SCDT_CONTINUE_LOGIN_INFO')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SCDT_CONTINUE_LOGIN_INFO = _descriptor.Descriptor(
  name='SCDT_CONTINUE_LOGIN_INFO',
  full_name='SCDT_CONTINUE_LOGIN_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='continue_days', full_name='SCDT_CONTINUE_LOGIN_INFO.continue_days', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_record_time', full_name='SCDT_CONTINUE_LOGIN_INFO.last_record_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='re_signable_days', full_name='SCDT_CONTINUE_LOGIN_INFO.re_signable_days', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_reward_bit', full_name='SCDT_CONTINUE_LOGIN_INFO.get_reward_bit', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=148,
)


_CSPKG_GET_CONLOGIN_REWARD = _descriptor.Descriptor(
  name='CSPKG_GET_CONLOGIN_REWARD',
  full_name='CSPKG_GET_CONLOGIN_REWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='con_login_type', full_name='CSPKG_GET_CONLOGIN_REWARD.con_login_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='day_num_reward', full_name='CSPKG_GET_CONLOGIN_REWARD.day_num_reward', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=225,
)


_SCPKG_NTF_CONLOGIN_REWARD = _descriptor.Descriptor(
  name='SCPKG_NTF_CONLOGIN_REWARD',
  full_name='SCPKG_NTF_CONLOGIN_REWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SCPKG_NTF_CONLOGIN_REWARD.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='con_login_type', full_name='SCPKG_NTF_CONLOGIN_REWARD.con_login_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='con_login_info', full_name='SCPKG_NTF_CONLOGIN_REWARD.con_login_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=345,
)


_SCPKG_GET_CONLOGIN_REWARD = _descriptor.Descriptor(
  name='SCPKG_GET_CONLOGIN_REWARD',
  full_name='SCPKG_GET_CONLOGIN_REWARD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SCPKG_GET_CONLOGIN_REWARD.result', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='con_login_type', full_name='SCPKG_GET_CONLOGIN_REWARD.con_login_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='con_login_info', full_name='SCPKG_GET_CONLOGIN_REWARD.con_login_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=465,
)

_SCPKG_NTF_CONLOGIN_REWARD.fields_by_name['con_login_info'].message_type = _SCDT_CONTINUE_LOGIN_INFO
_SCPKG_GET_CONLOGIN_REWARD.fields_by_name['con_login_info'].message_type = _SCDT_CONTINUE_LOGIN_INFO
DESCRIPTOR.message_types_by_name['SCDT_CONTINUE_LOGIN_INFO'] = _SCDT_CONTINUE_LOGIN_INFO
DESCRIPTOR.message_types_by_name['CSPKG_GET_CONLOGIN_REWARD'] = _CSPKG_GET_CONLOGIN_REWARD
DESCRIPTOR.message_types_by_name['SCPKG_NTF_CONLOGIN_REWARD'] = _SCPKG_NTF_CONLOGIN_REWARD
DESCRIPTOR.message_types_by_name['SCPKG_GET_CONLOGIN_REWARD'] = _SCPKG_GET_CONLOGIN_REWARD

SCDT_CONTINUE_LOGIN_INFO = _reflection.GeneratedProtocolMessageType('SCDT_CONTINUE_LOGIN_INFO', (_message.Message,), dict(
  DESCRIPTOR = _SCDT_CONTINUE_LOGIN_INFO,
  __module__ = 'continuelogin_pb2'
  # @@protoc_insertion_point(class_scope:SCDT_CONTINUE_LOGIN_INFO)
  ))
_sym_db.RegisterMessage(SCDT_CONTINUE_LOGIN_INFO)

CSPKG_GET_CONLOGIN_REWARD = _reflection.GeneratedProtocolMessageType('CSPKG_GET_CONLOGIN_REWARD', (_message.Message,), dict(
  DESCRIPTOR = _CSPKG_GET_CONLOGIN_REWARD,
  __module__ = 'continuelogin_pb2'
  # @@protoc_insertion_point(class_scope:CSPKG_GET_CONLOGIN_REWARD)
  ))
_sym_db.RegisterMessage(CSPKG_GET_CONLOGIN_REWARD)

SCPKG_NTF_CONLOGIN_REWARD = _reflection.GeneratedProtocolMessageType('SCPKG_NTF_CONLOGIN_REWARD', (_message.Message,), dict(
  DESCRIPTOR = _SCPKG_NTF_CONLOGIN_REWARD,
  __module__ = 'continuelogin_pb2'
  # @@protoc_insertion_point(class_scope:SCPKG_NTF_CONLOGIN_REWARD)
  ))
_sym_db.RegisterMessage(SCPKG_NTF_CONLOGIN_REWARD)

SCPKG_GET_CONLOGIN_REWARD = _reflection.GeneratedProtocolMessageType('SCPKG_GET_CONLOGIN_REWARD', (_message.Message,), dict(
  DESCRIPTOR = _SCPKG_GET_CONLOGIN_REWARD,
  __module__ = 'continuelogin_pb2'
  # @@protoc_insertion_point(class_scope:SCPKG_GET_CONLOGIN_REWARD)
  ))
_sym_db.RegisterMessage(SCPKG_GET_CONLOGIN_REWARD)


# @@protoc_insertion_point(module_scope)
