# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monster.proto',
  package='',
  serialized_pb=_b('\n\rmonster.proto\"V\n\x16\x43SDT_MONSTER_STAT_DATA\x12\x0c\n\x04stat\x18\x01 \x01(\r\x12\x15\n\rlv_cdbeg_time\x18\x02 \x01(\r\x12\x17\n\x0flv_cdtotal_time\x18\x03 \x01(\r\"e\n\x15\x43SDT_MONSTER_JOB_INFO\x12\x0e\n\x06volume\x18\x01 \x01(\r\x12\x17\n\x0flv_cost_crystal\x18\x02 \x01(\r\x12\x11\n\tcost_time\x18\x03 \x01(\r\x12\x10\n\x08grp_name\x18\x04 \x01(\t\"\xa1\x01\n\x16\x43SDT_MONSTER_INFO_DATA\x12\x16\n\x0emonster_grp_id\x18\x01 \x01(\r\x12\x11\n\tgrp_level\x18\x02 \x01(\r\x12*\n\tstat_info\x18\x03 \x01(\x0b\x32\x17.CSDT_MONSTER_STAT_DATA\x12\x30\n\x10monster_job_info\x18\x04 \x01(\x0b\x32\x16.CSDT_MONSTER_JOB_INFO\"F\n\x11\x43SDT_MONSTER_INFO\x12\x31\n\x10monster_grp_info\x18\x01 \x03(\x0b\x32\x17.CSDT_MONSTER_INFO_DATA\"\xa9\x01\n\x14SCDT_MONSTER_ATTINFO\x12\x0e\n\x06volume\x18\x01 \x01(\r\x12\x17\n\x0flv_cost_crystal\x18\x02 \x01(\r\x12\x14\n\x0clv_cost_gold\x18\x03 \x01(\r\x12\x14\n\x0clv_cost_time\x18\x04 \x01(\r\x12\x10\n\x08grp_name\x18\x05 \x01(\t\x12*\n\tstat_info\x18\x06 \x01(\x0b\x32\x17.CSDT_MONSTER_STAT_DATA\"T\n\x15SCDT_ROOMMONSTER_INFO\x12\x12\n\nmonster_id\x18\x01 \x01(\r\x12\x12\n\nmonster_lv\x18\x02 \x01(\r\x12\x13\n\x0bmonster_cnt\x18\x03 \x01(\r\"O\n\x0eSCDT_ROOM_INFO\x12\x0f\n\x07room_id\x18\x01 \x01(\r\x12,\n\x0cmonster_info\x18\x02 \x03(\x0b\x32\x16.SCDT_ROOMMONSTER_INFO\"\xb0\x01\n\x1bSCDT_UNLOCK_MONSTER_ATTINFO\x12\x0e\n\x06volume\x18\x01 \x01(\r\x12\x17\n\x0flv_cost_crystal\x18\x02 \x01(\r\x12\x14\n\x0clv_cost_gold\x18\x03 \x01(\r\x12\x14\n\x0clv_cost_time\x18\x04 \x01(\r\x12\x10\n\x08grp_name\x18\x05 \x01(\t\x12*\n\tstat_info\x18\x06 \x01(\x0b\x32\x17.CSDT_MONSTER_STAT_DATA')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CSDT_MONSTER_STAT_DATA = _descriptor.Descriptor(
  name='CSDT_MONSTER_STAT_DATA',
  full_name='CSDT_MONSTER_STAT_DATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='CSDT_MONSTER_STAT_DATA.stat', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cdbeg_time', full_name='CSDT_MONSTER_STAT_DATA.lv_cdbeg_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cdtotal_time', full_name='CSDT_MONSTER_STAT_DATA.lv_cdtotal_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=103,
)


_CSDT_MONSTER_JOB_INFO = _descriptor.Descriptor(
  name='CSDT_MONSTER_JOB_INFO',
  full_name='CSDT_MONSTER_JOB_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='CSDT_MONSTER_JOB_INFO.volume', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_crystal', full_name='CSDT_MONSTER_JOB_INFO.lv_cost_crystal', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost_time', full_name='CSDT_MONSTER_JOB_INFO.cost_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grp_name', full_name='CSDT_MONSTER_JOB_INFO.grp_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=206,
)


_CSDT_MONSTER_INFO_DATA = _descriptor.Descriptor(
  name='CSDT_MONSTER_INFO_DATA',
  full_name='CSDT_MONSTER_INFO_DATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster_grp_id', full_name='CSDT_MONSTER_INFO_DATA.monster_grp_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grp_level', full_name='CSDT_MONSTER_INFO_DATA.grp_level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat_info', full_name='CSDT_MONSTER_INFO_DATA.stat_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monster_job_info', full_name='CSDT_MONSTER_INFO_DATA.monster_job_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=370,
)


_CSDT_MONSTER_INFO = _descriptor.Descriptor(
  name='CSDT_MONSTER_INFO',
  full_name='CSDT_MONSTER_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster_grp_info', full_name='CSDT_MONSTER_INFO.monster_grp_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=442,
)


_SCDT_MONSTER_ATTINFO = _descriptor.Descriptor(
  name='SCDT_MONSTER_ATTINFO',
  full_name='SCDT_MONSTER_ATTINFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='SCDT_MONSTER_ATTINFO.volume', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_crystal', full_name='SCDT_MONSTER_ATTINFO.lv_cost_crystal', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_gold', full_name='SCDT_MONSTER_ATTINFO.lv_cost_gold', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_time', full_name='SCDT_MONSTER_ATTINFO.lv_cost_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grp_name', full_name='SCDT_MONSTER_ATTINFO.grp_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat_info', full_name='SCDT_MONSTER_ATTINFO.stat_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=614,
)


_SCDT_ROOMMONSTER_INFO = _descriptor.Descriptor(
  name='SCDT_ROOMMONSTER_INFO',
  full_name='SCDT_ROOMMONSTER_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monster_id', full_name='SCDT_ROOMMONSTER_INFO.monster_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monster_lv', full_name='SCDT_ROOMMONSTER_INFO.monster_lv', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monster_cnt', full_name='SCDT_ROOMMONSTER_INFO.monster_cnt', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=700,
)


_SCDT_ROOM_INFO = _descriptor.Descriptor(
  name='SCDT_ROOM_INFO',
  full_name='SCDT_ROOM_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_id', full_name='SCDT_ROOM_INFO.room_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monster_info', full_name='SCDT_ROOM_INFO.monster_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=702,
  serialized_end=781,
)


_SCDT_UNLOCK_MONSTER_ATTINFO = _descriptor.Descriptor(
  name='SCDT_UNLOCK_MONSTER_ATTINFO',
  full_name='SCDT_UNLOCK_MONSTER_ATTINFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.volume', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_crystal', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.lv_cost_crystal', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_gold', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.lv_cost_gold', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lv_cost_time', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.lv_cost_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grp_name', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.grp_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stat_info', full_name='SCDT_UNLOCK_MONSTER_ATTINFO.stat_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=784,
  serialized_end=960,
)

_CSDT_MONSTER_INFO_DATA.fields_by_name['stat_info'].message_type = _CSDT_MONSTER_STAT_DATA
_CSDT_MONSTER_INFO_DATA.fields_by_name['monster_job_info'].message_type = _CSDT_MONSTER_JOB_INFO
_CSDT_MONSTER_INFO.fields_by_name['monster_grp_info'].message_type = _CSDT_MONSTER_INFO_DATA
_SCDT_MONSTER_ATTINFO.fields_by_name['stat_info'].message_type = _CSDT_MONSTER_STAT_DATA
_SCDT_ROOM_INFO.fields_by_name['monster_info'].message_type = _SCDT_ROOMMONSTER_INFO
_SCDT_UNLOCK_MONSTER_ATTINFO.fields_by_name['stat_info'].message_type = _CSDT_MONSTER_STAT_DATA
DESCRIPTOR.message_types_by_name['CSDT_MONSTER_STAT_DATA'] = _CSDT_MONSTER_STAT_DATA
DESCRIPTOR.message_types_by_name['CSDT_MONSTER_JOB_INFO'] = _CSDT_MONSTER_JOB_INFO
DESCRIPTOR.message_types_by_name['CSDT_MONSTER_INFO_DATA'] = _CSDT_MONSTER_INFO_DATA
DESCRIPTOR.message_types_by_name['CSDT_MONSTER_INFO'] = _CSDT_MONSTER_INFO
DESCRIPTOR.message_types_by_name['SCDT_MONSTER_ATTINFO'] = _SCDT_MONSTER_ATTINFO
DESCRIPTOR.message_types_by_name['SCDT_ROOMMONSTER_INFO'] = _SCDT_ROOMMONSTER_INFO
DESCRIPTOR.message_types_by_name['SCDT_ROOM_INFO'] = _SCDT_ROOM_INFO
DESCRIPTOR.message_types_by_name['SCDT_UNLOCK_MONSTER_ATTINFO'] = _SCDT_UNLOCK_MONSTER_ATTINFO

CSDT_MONSTER_STAT_DATA = _reflection.GeneratedProtocolMessageType('CSDT_MONSTER_STAT_DATA', (_message.Message,), dict(
  DESCRIPTOR = _CSDT_MONSTER_STAT_DATA,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:CSDT_MONSTER_STAT_DATA)
  ))
_sym_db.RegisterMessage(CSDT_MONSTER_STAT_DATA)

CSDT_MONSTER_JOB_INFO = _reflection.GeneratedProtocolMessageType('CSDT_MONSTER_JOB_INFO', (_message.Message,), dict(
  DESCRIPTOR = _CSDT_MONSTER_JOB_INFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:CSDT_MONSTER_JOB_INFO)
  ))
_sym_db.RegisterMessage(CSDT_MONSTER_JOB_INFO)

CSDT_MONSTER_INFO_DATA = _reflection.GeneratedProtocolMessageType('CSDT_MONSTER_INFO_DATA', (_message.Message,), dict(
  DESCRIPTOR = _CSDT_MONSTER_INFO_DATA,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:CSDT_MONSTER_INFO_DATA)
  ))
_sym_db.RegisterMessage(CSDT_MONSTER_INFO_DATA)

CSDT_MONSTER_INFO = _reflection.GeneratedProtocolMessageType('CSDT_MONSTER_INFO', (_message.Message,), dict(
  DESCRIPTOR = _CSDT_MONSTER_INFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:CSDT_MONSTER_INFO)
  ))
_sym_db.RegisterMessage(CSDT_MONSTER_INFO)

SCDT_MONSTER_ATTINFO = _reflection.GeneratedProtocolMessageType('SCDT_MONSTER_ATTINFO', (_message.Message,), dict(
  DESCRIPTOR = _SCDT_MONSTER_ATTINFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:SCDT_MONSTER_ATTINFO)
  ))
_sym_db.RegisterMessage(SCDT_MONSTER_ATTINFO)

SCDT_ROOMMONSTER_INFO = _reflection.GeneratedProtocolMessageType('SCDT_ROOMMONSTER_INFO', (_message.Message,), dict(
  DESCRIPTOR = _SCDT_ROOMMONSTER_INFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:SCDT_ROOMMONSTER_INFO)
  ))
_sym_db.RegisterMessage(SCDT_ROOMMONSTER_INFO)

SCDT_ROOM_INFO = _reflection.GeneratedProtocolMessageType('SCDT_ROOM_INFO', (_message.Message,), dict(
  DESCRIPTOR = _SCDT_ROOM_INFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:SCDT_ROOM_INFO)
  ))
_sym_db.RegisterMessage(SCDT_ROOM_INFO)

SCDT_UNLOCK_MONSTER_ATTINFO = _reflection.GeneratedProtocolMessageType('SCDT_UNLOCK_MONSTER_ATTINFO', (_message.Message,), dict(
  DESCRIPTOR = _SCDT_UNLOCK_MONSTER_ATTINFO,
  __module__ = 'monster_pb2'
  # @@protoc_insertion_point(class_scope:SCDT_UNLOCK_MONSTER_ATTINFO)
  ))
_sym_db.RegisterMessage(SCDT_UNLOCK_MONSTER_ATTINFO)


# @@protoc_insertion_point(module_scope)
